<a href="https://colab.research.google.com/github/ShibuGitB/CognoRise_InfoTech/blob/main/Task_1_CognoRise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Importing Necessary Packages***

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error,mean_squared_error

***Dataset***

In [ ]:
dataset=pd.read_csv("/content/drive/MyDrive/Task 1 CognoRise/data.csv")
dataset

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09 00:00:00,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

***Droping Unwanted Columns***

In [ ]:
dataset.drop(["date"],axis=1,inplace=True)

In [ ]:
dataset.dtypes

price            float64
bedrooms         float64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
street            object
city              object
statezip          object
country           object
dtype: object

***Converting String columns to Numeric value***

In [ ]:
columns=["street","city"]

for i in columns :

  encoder=LabelEncoder()
  encoder.fit(dataset[i])
  dataset[i]=encoder.transform(dataset[i])

In [ ]:
dataset

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,1522,36,WA 98133,USA
1,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,3899,35,WA 98119,USA
2,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,2291,18,WA 98042,USA
3,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,4263,3,WA 98008,USA
4,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,4352,31,WA 98052,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,3447,35,WA 98133,USA
4596,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,960,3,WA 98007,USA
4597,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,4033,32,WA 98059,USA
4598,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,3498,35,WA 98178,USA
4599,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,1514,9,WA 98042,USA

In [ ]:
dataset["statezip"]=dataset["statezip"].str.replace("WA","")

In [ ]:
dataset["statezip"]=dataset["statezip"].astype(float)

In [ ]:
dataset["country"]=dataset["country"].map({"USA":1})

In [ ]:
dataset.dtypes

price            float64
bedrooms         float64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
street             int64
city               int64
statezip         float64
country            int64
dtype: object

***Pre-Processed Dataset***

In [ ]:
dataset

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,1522,36,98133.0,1
1,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,3899,35,98119.0,1
2,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,2291,18,98042.0,1
3,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,4263,3,98008.0,1
4,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,4352,31,98052.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,3447,35,98133.0,1
4596,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,960,3,98007.0,1
4597,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,4033,32,98059.0,1
4598,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,3498,35,98178.0,1
4599,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,1514,9,98042.0,1

In [ ]:
dataset.isna().sum()

price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

***Seperating Input & Output***

In [ ]:
input=dataset.iloc[:,1:]

In [ ]:
output=dataset.iloc[:,0]

***Taking input & output for the Training & Testing***

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(input,output,test_size=0.3,random_state=1)

***Applying algorithms and making models and checking accuracybto take a best model***

In [ ]:
model1=LinearRegression(fit_intercept=True,copy_X=True,n_jobs=1,positive=True)
model1.fit(x_train,y_train)
y_pred=model1.predict(x_test)

In [ ]:
print (r2_score(y_test,y_pred))

0.4381090083949053

In [ ]:
model2=DecisionTreeRegressor(criterion='squared_error', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, ccp_alpha=0.0)
model2.fit(x_train,y_train)
y_pred2=model2.predict(x_test)

In [ ]:
print (r2_score(y_test,y_pred2))

-7.1566210754469886

In [ ]:
model3=RandomForestRegressor(n_estimators=100, criterion='squared_error', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=1.0, max_leaf_nodes=None, min_impurity_decrease=0.0, bootstrap=True, oob_score=False, n_jobs=None, random_state=1, verbose=0, warm_start=False, ccp_alpha=0.0, max_samples=None)
model3.fit(x_train,y_train)
y_pred3=model3.predict(x_test)

In [ ]:
print (r2_score(y_test,y_pred3)*100)

8.088897865263057

In [ ]:
model4=AdaBoostRegressor(estimator=None,learning_rate=1.0,loss="linear",n_estimators=50,random_state=1)
model4.fit(x_train,y_train)
y_pred4=model4.predict(x_test)

In [ ]:
print (r2_score(y_test,y_pred4))

0.1881932902759187

In [ ]:
model5=XGBRegressor(loss='squared_error', learning_rate=0.1, n_estimators=100, subsample=1.0, criterion='friedman_mse', min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_depth=3, min_impurity_decrease=0.0, init=None, random_state=None, max_features=None, alpha=0.9, verbose=0, max_leaf_nodes=None, warm_start=False, validation_fraction=0.1, n_iter_no_change=None, tol=0.0001, ccp_alpha=0.0)
model5.fit(x_train,y_train)
y_pred5=model5.predict(x_test)

/usr/local/lib/python3.10/dist-packages/xgboost/core.py:160: UserWarning: [10:32:18] WARNING: /workspace/src/learner.cc:742:
Parameters: { "ccp_alpha", "criterion", "loss", "min_impurity_decrease", "min_samples_leaf", "min_samples_split", "min_weight_fraction_leaf", "tol", "validation_fraction", "verbose", "warm_start" } are not used.

  warnings.warn(smsg, UserWarning)

In [ ]:
print (r2_score(y_pred5,y_test))

0.23604493041096708

In [ ]:
model6=Lasso(alpha=1.0, fit_intercept=True, precompute=False, copy_X=True, max_iter=1000, tol=0.0001, warm_start=False, positive=False, random_state=None, selection='cyclic')
model6.fit(x_train,y_train)
y_pred6=model6.predict(x_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.788e+14, tolerance: 1.279e+11
  model = cd_fast.enet_coordinate_descent(

In [ ]:
print (r2_score(y_test,y_pred6))

0.4761750427117345

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
model8=KNeighborsRegressor(n_neighbors=5, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=None)
model8.fit(x_train,y_train)
y_pred8=model8.predict(x_test)

In [ ]:
print (r2_score(y_test,y_pred8))

-0.3104253008832485

In [ ]:
model7=Ridge(alpha=1.0, fit_intercept=True, copy_X=True, max_iter=None, tol=0.0001, solver='auto', positive=False, random_state=None)
model7.fit(x_train,y_train)
y_pred7=model7.predict(x_test)

In [ ]:
print (r2_score(y_test,y_pred7))

0.4778245608759558

***Took Ridge Regression Model at almost accuracy of 47% ,corresponding to other models it would better***

In [ ]:
import warnings
warnings.filterwarnings("ignore")

***Taking prediction by sample input***

In [ ]:
prediction=model7.predict([[3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,1522,36,98133.0,1]])
print ("House Rate by corresponding Details =",prediction.item())

House Rate by corresponding Details = 372168.20980934054